### ISSUE TITLE
token_validation_failed

### ISSUE THREAD

**Issue by b-rohit** [mindsphere/mindconnect-nodejs#106]
**Describe the bug**
I got the error Network error occurred `Network error occured Unauthorized {"error":"token_validation_failed"` while using mc command. It works fine with MindConnect Node-Red Agent node.

**To Reproduce**
1. install mindconnect
`npm install -g @mindconnect/mindconnect-nodejs@latest`
```
$mc --version
MindConnect NodeJS CLI - Version: 3.6.1
```
2. create agentconfig.json based on info from mindsphere
3. run command `mc onboard -c ./agentconfig.json`

**Expected behavior**
It should connect to agent.

**Screenshots**
I get following error when I try to on-board an agent.
```
$mc onboard -c ./agentconfig.json
...Retry no 1 for OnBoard operation.
...Retry no 2 for OnBoard operation.

Network error occured Unauthorized {"error":"token_validation_failed","error_description":"[6f7c7c836d3043b498b28a46d5f8a201]"}
```
[https://github.com/mindsphere/mindconnect-nodejs/issues/82](https://github.com/mindsphere/mindconnect-nodejs/issues/82)

**Desktop (please complete the following information):**
 - OS : "16.04.6 LTS (Xenial Xerus)"
 - Node : v12.13.1
 - npm : v6.12.1

**Comment by sn0wcat** [comment]
You shouldn’t use the same configuration (agentconfig.json)  for the node-red an for your command line tools. The agents have state which is stored for command line in the HOME/.mc folder and for node-red in home/.node-red/.mc/ Folder.  See also #3
