### ISSUE TITLE
Posted Data doesn't appear in FleetManager

### ISSUE THREAD

**Issue by schaefersimon** [mindsphere/mindconnect-nodejs#148]
After agent and iot-model (asset) has been mapped I tried to post data. I first tried to do so with PostData() after that I tried BulkPostData. In both cases the function returned true and I didn't receive any errors but the data doesn't appear in the Fleet Manager.

            this.motorSpeed= dataValue1.value.value as number; 
            let val = dataPointValues.find(el => el.dataPointId === myId);

            val.value = this.motorSpeed.toString();
            val.qualityCode = 'true';

            const bulkData: TimeStampedDataPoint[] = [
                {
                    timestamp: new Date().toString(),
                    values: dataPointValues
                }                
            ]

            let posted = await myMindConnectLib.agent.BulkPostData(bulkData);

**Comment by sn0wcat** [comment]
have you taken a look at the diagnostic in the diagnotic app in mindsphere if there is a problem?
the library unfortunately can't know if there is a problem with the mappings b/c the mindsphere endpoint returns 200 ok when the data arrives and the rest of the processing is asynchronous.

https://opensource.mindsphere.io/docs/mindconnect-nodejs/troubleshooting.html#tab1anchor2

**Comment by schaefersimon** [comment]
Thanks for the advice to use the Diagnostic tool. The data has been dropped due to a invalid timestamp!
