### ISSUE TITLE
Acquiring an Agent Access Token

### ISSUE THREAD

**Issue by mshafieluru** [mindsphere/mindconnect-nodejs#149]
**Is your feature request related to a problem? Please describe.**
Where does the Acquiring of an Agent Access Token is handled in node.js code ? is this step automatically takes care of 1 hour of refreshing the token ?

**Describe the solution you'd like**
I want to start sending code from IoT device to Mindsphere using node.js code

**Describe alternatives you've considered**

**Additional context**

**Comment by sn0wcat** [comment]
Every operation calls RenewToken implicitely which handles the acquiring of the access token, which is normally sufficient if your agent is running all the time. 

If your agent is calling MindSphere APIs only occasionally the authentication secrets might expire.  If you are writing a custom agent make sure that you are doing something like this:

```javascript
setInterval (async () => {
  await retry (5, ()=>agent.RenewToken());
}, 3600000)
```

See also :

https://opensource.mindsphere.io/docs/mindconnect-nodejs/troubleshooting.html#tab1anchor3

**Comment by mshafieluru** [comment]
This below code is not working 

`import { MindConnectAgent, DataPointValue } from "@mindconnect/mindconnect-nodejs";

const configuration = require("config.json");
const agent = new MindConnectAgent(configuration);

if (agent.IsOnBoarded()) {
    console.log("The agent is already onboarded!");
}

if (agent.HasDataSourceConfiguration()) {
    console.log("Data Source Configuration is acquired!");
}

for (let i = 1; i < 6; i++) {

    const values: DataPointValue[] = [
        { "dataPointId": "CO2", "qualityCode": "0", "value": (400 + i).toString() },
        { "dataPointId": "VOC", "qualityCode": "0", "value": (0.1 + (i / 10)).toString() }
    ];

    const result = await agent.PostData(values);
	console.log("Result .." + result);
}`

I have installed node.js and mindconnect as explained in the documentation. The mc tool also is working fine

Can you provide me with working node.js code to run it from Debian run time of my IoT Box

**Comment by sn0wcat** [comment]
that looks fine (if the configuration is correct and data mappings as well).

Please take a look at the agent diagnostic app in the mindsphere (on your mindsphere dashboard) if everything is configured properly.

https://opensource.mindsphere.io/docs/mindconnect-nodejs/troubleshooting.html#tab1anchor2

Hint: 

if you have configured the configuration / mappings in mindsphere ui, you have to use the long integer dataPointIds instead.

**Comment by mshafieluru** [comment]
The import statements in line 1 are failing
I tried with just using require as well.
Thanks. I will further investigate this

**Comment by sn0wcat** [comment]
@mshafieluru which node version are you using? (node --version)

**Comment by mshafieluru** [comment]
v10.12.0

**Comment by mshafieluru** [comment]
I have full control on it. I can re-install to the version you specify

**Comment by sn0wcat** [comment]
10.12. should be fine

maybe you could delete your node_modules folder and run npm install again just to make sure that you have all dependencies.

**Comment by mshafieluru** [comment]
![image](https://user-images.githubusercontent.com/5220761/84120600-576df000-aa36-11ea-8d33-3bdaf24cb830.png)

Can you tell me inside which directory i should run this node <myfile.js> command
I am running it from where my js file and json files are stored.

**Comment by sn0wcat** [comment]
@mshafieluru 

it looks to me as if you have typescript / ecmascript6 syntax for module imports inside of a javascript file. 

nodejs doesn't support import statements in javascript files without the --experimental-modules switch.

```bash
node --experimental-modules myfile.js
```

Btw, the library comes with the starter project generator which can generate project skeleton for typescript of javascript.

```bash
npm install -g @mindconnect/mindconnect-nodejs

# create starter project for typescript
mc starter-ts

# create starter project for javascript
mc starter-ts
```

Step by step guide for typescript:

https://opensource.mindsphere.io/docs/mindconnect-nodejs/agent-development/starter-projects.html

**Comment by mshafieluru** [comment]
The first command itself is failing
mc createts --dir my-agent
or 
mc starter-ts

![image](https://user-images.githubusercontent.com/5220761/84128063-5a6dde00-aa40-11ea-85e2-1dc9ae3d8c35.png)

I will try out couple of other configurations and let you know

**Comment by mshafieluru** [comment]
Hi

Thank you very much for your last reply and it works fine.... Minor updates to the documentation are required. But its working fine for me

I can see the events arriving in my IoT Tenant in Mindsphere

The data is posted though. I do not know how to see it

Regards
Shafi

**Comment by sn0wcat** [comment]
you can see the data in fleet manager. If there are problems with mappings, configuration etc. you can always take a look at the AgentDiagnosticApp on the dashboard.
