### ISSUE TITLE
Configure data source and the related data mapping

### ISSUE THREAD

**Issue by alessandrochetta** [mindsphere/mindconnect-nodejs#167]
Is it possible to create a data source and the related data mapping using this library? If not I'd like to have this functionality. In the repository readme I can see that the creation of data source and data mapping is done through the interface.

**Comment by sn0wcat** [comment]
@alessandrochetta 

it is possible however until recently it wasn't possible to read asset information and to create the mappings without knowing the asset type information from some other source. you could always create both:

- data source configuration ```await agent.PutDataSourceConfiguration()``` 
- and mappings ```await agent.PutMappings()``` 

but you needed the target information of the asset and agents couldn't read that...

now that that has changed the next version will have also automatic creation of data source configuration and mappings;

``` typescript
 const agent = new MindConnectAgent(agentConfig);
        if (!agent.IsOnBoarded()) {
            await agent.OnBoard();
        }

        const targetAssetId = "123....";
        await agent.ConfigureAgentForAssetId(targetAssetId);
   
        for (let index = 0; index < 15; index++) {
            const values: DataPointValue[] = [
                { dataPointId: "DP-Temperature", qualityCode: "0", value: "223.1" },
                { dataPointId: "DP-Pressure", qualityCode: "0", value: "244" },
                { dataPointId: "DP-Humidity", qualityCode: "0", value: "366" },
            ];

            await agent.PostData(values);
}
```
You can test that already now by installing the alpha version of the library. ```npm install @mindconnect/mindconnect-nodejs@alpha --save```

**Comment by sn0wcat** [comment]
the support for this is now on master branch @alessandrochetta , you can take a look at the README.md

**Comment by alessandrochetta** [comment]
Thank you so much, I'll test it out.

**Comment by sn0wcat** [comment]
for future reference (and google search ;) The CLI can do this too:

![image](https://user-images.githubusercontent.com/1426617/85703208-6d8ada00-b6df-11ea-8a3f-1154b493acf8.png)
