### ISSUE TITLE
feat: add the digital twin type option to create-asset command

### ISSUE THREAD

**Issue by sn0wcat** [mindsphere/mindconnect-nodejs#194]
If you have never contributed to open source here is your chance: 😸 

[0] Comment on this issue that you will take care of this feature impementation ;)
[1] fork the repository (click on the Fork button)
[2] Clone it to your local system and install the dependencies by running `npm install` in the cloned directory. (you will need nodejs in your development environment)
[3] Implement the feature

in the `src/cli/commands/create-asset.ts"

Add the option --twintype to the .options part of the code between desc and passkey option

```typescript
.option("-w, --twintype <twintype>", "digital twin type [performance|simulation]")
```
add the twinType to the PostAsset method like this

```typescript
                    const result = (await retry(options.retry, async () =>
                        assetMgmt.PostAsset({
                            name: options.assetname,
                            parentId: options.parentid || (await assetMgmt.GetRootAsset()).assetId!,
                            externalId: options.externalid,
                            typeId: options.typeid,
                            description: options.desc,
                            twinType: options.twintype || AssetManagementModels.TwinType.Performance
                        })
                    )) as AssetManagementModels.AssetResourceWithHierarchyPath;
```

add the following check to the `checkRequiredParameters` method

```typescript
options.twintype &&
        !["performance", "simulation"].includes(options.twintype) &&
        errorLog("the twin type must be either performance or simulation", true);
```

You are done. 🎉  🎶 😸 👍 

[4] Push the changes back to your repository
[5] Click the Compare & pull request button.
[6] Click Create pull request to open a new pull request.

See also: 

https://opensource.com/article/19/7/create-pull-request-github

Happy Hacktoberfest! 

https://hacktoberfest.digitalocean.com/

**Comment by RhnSaxena** [comment]
@sn0wcat I have raised pull request #195 for this issue.
