### ISSUE TITLE
Failed to upload Time Series Data in version 3.4.0

### ISSUE THREAD

**Issue by favccxx** [mindsphere/mindconnect-nodejs#20]
**Describe the bug**
I tried to upload Time Series Data with mc, but it failed with timestamp data, It's sucessful upload file & event. Below is the error info.

D:\dev\mindsphere\mindconnect-nodejs-3.4.0> mc ts -f data\1.csv
... posting timeseries message Nr. 1 with 3 records
Retry no 1 for TimeSeriesBulkUpload operation.
Retry no 2 for TimeSeriesBulkUpload operation.
property path: "timestamp" not valid in your data at object: {"dataPointId":"DP-Temperature","qualityCode":"0","value":"20.34"}

1.csv is my data.
timestamp, dataPointId, qualityCode, value
2019-04-09T09:18:21.809Z, DP-Temperature ,0, 20.34
2019-04-09T09:18:22.809Z, DP-Humidity, 0, 70.4
2019-04-09T09:18:23.809Z, DP-Pressure, 0, 1012.3

Version: 3.4.0

**Comment by sn0wcat** [comment]
@favccxx  I guess you have used the same model like in the README.md. Your Humidity is a double value (70.4) but in the definition it is an integer.

This works:

```
timestamp, dataPointId, qualityCode, value
2019-04-09T09:18:21.809Z, DP-Temperature, 0, 20.34
2019-04-09T09:18:22.809Z, DP-Humidity, 0, 70
2019-04-09T09:18:23.809Z, DP-Pressure, 0, 1012.3
```

I will take a look if we can improve the error message a little bit there

**Comment by sn0wcat** [comment]
chore: improve the error message which happens during CSV parsing.

**Comment by favccxx** [comment]
It worked after i changed the datatype, I mistake something wrong with timestamp. Thanks.
