### ISSUE TITLE
feat: support onboarding mindconnect elements through CLI

### ISSUE THREAD

**Issue by dremsol** [mindsphere/mindconnect-nodejs#233]
Onboarding a large amount of MindConnect Elements (IoT2040/Nano) through the UI is a hassle and time-consuming task. Therefore we have been using our own scripts using the several (non-public) API's necessary to accomplish this task. However, it would be nice if these features can be supported in this CLI. The procedure which we are following today is more or less as follows;

1. Create virtual asset hierarchy from custom specification.
2. On-boarding MindConnect Elements by creating an asset of type `core.iot2040` or `core.nano` and at it to a certain place in the asset hierarchy. Consequently generate a USB file with the required on-boarding config and onboard the device.
3. Upload datasource configuration to Agent.
4. Create datamapping between virtual and physical assets by connecting variables and datapoints respectively.

The above is dependent on `mindconnectdevicemanagement` API which is not public at time of writing. Would love to hear your thoughts on the above and if this is a feature to include.

**Comment by sn0wcat** [comment]
I agree that it would be great to include this feature.  However, as long as the APIs are not public, I can't include the support for them in the library. It would be a good idea to create an issue on your mindsphere tenant requesting to make this API public....

**Comment by sn0wcat** [comment]
I will ask internally if this API will be public any time soon.,,

**Comment by dremsol** [comment]
Hi @sn0wcat, all the information I got so far regarding the API i got directly from C. Hirth. Would be good to double check with him. Anyway, I also created an issue through regular support channels with ID #9981423

**Comment by SamWenz** [comment]
Hi @dremsol. We have build the Connectivity Extension https://www.dex.siemens.com/mindsphere/applications/connectivity-extension?viewState=DetailView&cartID=&portalUser=&store=&cclcl=en_US and the Visual Hierarchy Modeler. https://www.dex.siemens.com/mindsphere/applications/visual-hierarchy-modeler  I think some of your requests are solved with this apps.  Let's talk! best regards,
Samuel

**Comment by sn0wcat** [comment]
closing the issue, will reopen it once the api is public.

**Comment by dremsol** [comment]
Hi @sn0wcat, any updates on this feature request and/or public API release?

**Comment by sn0wcat** [comment]
@dremsol mr Hirth has to make the API public first ;)
