### ISSUE TITLE
Feature request: IAT via msg property

### ISSUE THREAD

**Issue by na-am** [mindsphere/mindconnect-nodejs#235]
hi Sn0wcat

it would be great to have a msg property, e.g. msg.iat to set the IAT in the MCL node from a global variable in my case.
That would be easier and faster to onbard a huge amount of agents because currently i'm setting all parameters/datapoints via a config file that Node-red is automacically reading from the device on startup. The IAT is the only parameter that must be copied 'by hand'.

thx
na-am

**Comment by sn0wcat** [comment]
@na-am my guess is that this was meant for the mindconnect node-red node and not the library. Anyhow, you can send already now a full configuration object to the node via flow which also contains IAT, the node will even restart the flow after receiving the new configuration

```
msg.payload ={
    "name": "Managed Configuration",
    "configtype": "SHARED_SECRET",
    "agentconfig": {
        "content": {
            "baseUrl": "https://southgate.eu1.mindsphere.io",
            "iat": "xxx",
            "clientCredentialProfile": ["SHARED_SECRET"],
            "clientId": "xxx",
            "tenant": "xxx"
        },
        "expiration": "2018-11-15T17:31:35.000Z"
    },
    "privatekey": "",
    "model": "",
    "validate": true,
    "validateevent": true,
    "chunk": true,
    "disablekeepalive": false,
    "retry": "5",
    "parallel": "7",
    "asyncduration": "10"
}
```

**Comment by sn0wcat** [comment]
as this is already implemented I will close the issue :)
