### ISSUE TITLE
Change default config folder to ~/.mc/

### ISSUE THREAD

**Issue by Chris1209** [mindsphere/mindconnect-nodejs#3]
**Is your feature request related to a problem? Please describe.**
Currently, the agent's config is stored in .mc/. So you need to take care of always launching the agent from the same location, which is especially annoying when using it via the mindconnect node in Node Red. 

**Describe the solution you'd like**
Change the config folder to ~/.mc/

**Comment by sn0wcat** [comment]
@Chris1209 


The CLI home directory is already ~/.mc/. Unfortunately moving the default config folder to ~/,mc/  without any mitigation would break compatibility with the previous versions of the library. 

I will see what we can do, but until then you can work around the problem by creating a symlink from your .node-red folder to your home folder. (this is how my local computer is set up too.)

```bash
drwxr-xr-x 1 sn0wcat 1049089     0 Jan 28 02:40 .
drwxr-xr-x 1 sn0wcat 1049089     0 Jan 24 12:56 ..
lrwxrwxrwx 1 z001ythk 1049089    21 Jan 24 01:16 .mc -> /c/Users/sn0wcat/.mc
```
