### ISSUE TITLE
[dev-proxy] MindSphere asset web components fails to load assets with newer browser versions

### ISSUE THREAD

**Issue by TrevorOchmonek** [mindsphere/mindconnect-nodejs#302]
The dev-proxy used to work with Chrome 95.x (don't remember the exact version). After updating to 96.0.4664.45 the "mdsp-asset-view" web component keeps showing the loading indicator (spinning wheel) forever.

We have an older version of the deprecated _mindsphere-development-proxy-master 1.0.2_ which uses service credentials for authentication and this still works even with the current Chrome browser.

**To Reproduce**
1. run mc px -m credentials ....
2. open web page containing <mdsp-asset-view> web component element
3. loading indicator spins forever

**Comment by sn0wcat** [comment]
@TrevorOchmonek are there any errors indicated in the chrome console when loading the component. //cc : @gesslinger

**Comment by TrevorOchmonek** [comment]
@sn0wcat nope, no errors

**Comment by TrevorOchmonek** [comment]
@sn0wcat yes that property was already added and set to true but it had no impact on the result. The web control seems to hang at some point so even error messages don't get processed.
