### ISSUE TITLE
The IDL upload not work for alibaba cloud of mindsphere

### ISSUE THREAD

**Issue by nrh387** [mindsphere/mindconnect-nodejs#316]
**Describe the bug**
For alibaba cloud mindsphere, upload the file to datelake, the header need add the "Content-Type": "application/octet-stream", this is not need for eu1 and eu2 platform, but that's need for ali platform.

https://github.com/mindsphere/mindconnect-nodejs/blob/master/src/api/sdk/data-lake/data-lake.ts

Suggest add the logic check for alibaba signedURL as below:

   public async PutFile(file: string | Buffer, signedUrl: string): Promise<Headers> {
        const myBuffer = typeof file === "string" ? fs.readFileSync(file) : (file as Buffer);

        const proxy = process.env.http_proxy || process.env.HTTP_PROXY;
        const proxyHttpAgent: any = proxy ? new HttpsProxyAgent(proxy) : null;

        let headers;

        if (signedUrl.match(".*oss-.*.aliyuncs.com.*") != null ) {
            /**
             * In case of MindSphere in Alibaba cloud,
             * it needs to set content-type to be 'application/octet-stream' when to put file to data lake.
             */
            headers = { "Content-Type": "application/octet-stream" };
        } else {
            headers = { "x-ms-blob-type": "BlockBlob" }
        }

        // x-ms-blob is necessary on eu2 and is ignored on eu1
        const request: any = { method: "PUT", headers: headers, agent: proxyHttpAgent };
        request.body = myBuffer;
        const response = await fetch(signedUrl, request);
        return response.headers;
    }

**Comment by sn0wcat** [comment]
@nrh387 I will add the support in the next version of the library. In the mean time as a workaround, you can use the node just to generate the signed URL (but don't do the upload) and do the actual file upload with standard node-red http nodes , while adding the necessary header. Sorry that i missed that, I don't have access to mindsphere on ALI...

``` javascript
// Uncomment the next code line if you just want to generate an upload url (in msg._signedUrl) 
// without actually uploading the file
msg._ignorePayload = true;
```

so that the node

**Comment by nrh387** [comment]
Yes, i try to do that, but it looks it hard for me to pass the signed URL to standard node-red http node, the http node not accept the msg.payload from previous node.
![image](https://user-images.githubusercontent.com/19149590/165924233-6190e813-e129-4f2b-98c5-83a2b34614e1.png)

**Comment by sn0wcat** [comment]
@nrh387  any luck?

**Comment by nrh387** [comment]
![image](https://user-images.githubusercontent.com/19149590/166893932-dfb73ac5-3c39-40f7-96e1-c0c8416692d5.png)
I have install the alpha version, but it looks still not work for me

**Comment by nrh387** [comment]
from code perspective, it looks ok to check the alibaba gateway address. Is there any debug information could get from node red?

![image](https://user-images.githubusercontent.com/19149590/166912191-92e2c46b-af09-4daf-83c5-3b58e60def90.png)

**Comment by sn0wcat** [comment]
@nrh387 I've just gotten access to a tenant in CN, I have the same behavior, looking into it.

**Comment by sn0wcat** [comment]
@nrh387 I got it running ;) It was my fault , I told you to install the alpha in the wrong directory, the correct one for hacking the dependency is 

![image](https://user-images.githubusercontent.com/1426617/166927911-2ccd837a-438f-4586-b14a-494171127c7f.png)

It is working now, the example is here:

https://playground.mindconnect.rocks/#flow/5eda11af.df734

![image](https://user-images.githubusercontent.com/1426617/166928178-5afff60f-10e9-4596-8dc0-7ac9044b60c7.png)

I will release a new version some time later today, which should work as expected ;)

**Comment by sn0wcat** [comment]
@nrh387 the release is out, uninstalling and reinstalling the node so that it picks up the 3.19.0 version of the library should fix the problem.

**Comment by nrh387** [comment]
Yes, i verified and it works. Thanks so much @sn0wcat

**Comment by nrh387** [comment]
@sn0wcat  May i know if the latest docker image have been updated for this change or not?  Right now, i fixed it with npm install manually. https://hub.docker.com/r/mindconnect/node-red-contrib-mindconnect

**Comment by sn0wcat** [comment]
Not yet, sorry I forgot to start the docker image build I will take care of it today ...

**Comment by nrh387** [comment]
@sn0wcat  that's great, please let me know when the docker image have been pushed to docker hub. Thanks a lot
