### ISSUE TITLE
IoT Time Series command in CLI

### ISSUE THREAD

**Issue by dremsol** [mindsphere/mindconnect-nodejs#318]
Unless i'm missing something it seems the CLI only contains a command for listing IoT TS Aggregates and no IoT Time Series as indicated by the docs.

**Comment by sn0wcat** [comment]
there id a `mc download-bulk` command for downloading the Timeseries data in a bulk form.  I haven't made a `mdsp timeseries` command before on purpose, because i was putting too much load on the API but I guess now would be a good time to add one ;)
