### ISSUE TITLE
add support for RAM - Resource Access Management

### ISSUE THREAD

**Issue by ChristophDoehl** [mindsphere/mindconnect-nodejs#327]
MindSphere provides policies support to manage what user has access to what asset tree. 
CLI should support creation and configuration of policies
more to be found here: https://documentation.mindsphere.io/MindSphere/apis/core-resourceaccessmanagement/api-resourceaccessmanagement-overview.html

**Comment by sn0wcat** [comment]
the polciies client is there since few versions already.
