### ISSUE TITLE
CLI 3.22.0 - Tuscan Sun Vienna - November 2022 does not work on Ubuntu 20.04.03

### ISSUE THREAD

**Issue by th-buchner** [mindsphere/mindconnect-nodejs#342]
Downloaded the  3.22.0 - Tuscan Sun Vienna - November 2022 Linux executable of mc-linux and installed on my WSL2 version of Ubuntu 20.04.03.

Started with
`./mc-linux`

got this error

`qemu-aarch64: Could not open '/lib/ld-linux-aarch64.so.1': No such file or directory`

Previous versions started without error

Regards Thomas 

P.S. We are collegues in MindSphere ;)

**Comment by sn0wcat** [comment]
as a workaround please install the nodejs version ,i will look into it

**Comment by sn0wcat** [comment]
I exchanged the version in the release, the previous version was built on mac using qemu, this should hopefully work:

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/1426617/217843159-bbe32ddd-701d-4403-984f-7989b5c5cd2f.png">

**Comment by th-buchner** [comment]
@sn0wcat - yes, works on my WSL2 version of Ubuntu 20.04.03

Thanks
