### ISSUE TITLE
Inconsistent Data Upload

### ISSUE THREAD

**Issue by kaischwetz** [mindsphere/mindconnect-nodejs#61]
Hello everyone,
I have an upload problem with the postData method of the mindConnectAgent.
If I upload many data points in a short time frame data points are discarded by the agent without any error (return value of postData is true, no exception thrown)

**Describe the bug**
I have three post data requests every 10 seconds which upload up to 10 data points each.
In this scenario, everything works well most of the time and the data is complete, but if I increase the upload frequency of the requests from 6 uploads/min to 60 uploads/min some data points don’t show up in MindSphere (Timeseries API).

I have tracked my data to the internal postData method of MindConnect-Agent class, where the data is still complete.
But if I now check with postman whether all data have been uploaded successfully, several data points are missing again and again.

**To Reproduce**
-Send up to three postData requests every second with round about 10 data points for at least 60 seconds.

**Expected behavior**
The agent should always upload all data points, return false or throw an exception.

**Desktop**
OS: WSL
NPM Version: 6.4.1
Node Version: 10.15.1
MindConnect-Nodejs Version: 3.5.3

**Additional context**
I also checked the Record Recovery endpoint to see if there is a reason for the missing data, but there is no record generated which says that some data points failed to upload.

Is it possible that the postData method from the agent has an internal limitation that blocks some requests or parts of a request if there are too many in a short time?

**Comment by sn0wcat** [comment]
@kaischwetz 

Can you please register your agent for diagnostics

https://opensource.mindsphere.io/docs/mindconnect-nodejs/cli/agent-diagnostic.html

(or using the application AgentDiagnostic on your launchpad), run the agent and see if there are any problems.

are you waiting for post data to return ? (await agent.PostData() ?) It might be that you are getting exceptions on your client side which get swallowed because of missing await. 

There is nothing special about the postdata method, it just makes a normal http post.

**Comment by sn0wcat** [comment]
@kaischwetz if it is not too much trouble, could you also post your main loop where you are posting the data here?

**Comment by kaischwetz** [comment]
> @kaischwetz
> 
> Can you please register your agent for diagnostics
> 
> https://opensource.mindsphere.io/docs/mindconnect-nodejs/cli/agent-diagnostic.html
> 
> (or using the application AgentDiagnostic on your launchpad), run the agent and see if there are any problems.


Hey @sn0wcat,
I have now registered my agent to the application AgentDiagnostic. Here it is now noticeable that the values I miss are skipped here. Normally another entry in second 47 should be processed between second 46 and 48.

![image](https://user-images.githubusercontent.com/47818788/60659196-1ef08a00-9e55-11e9-8bf4-bb5bb2188227.png)



> 
> are you waiting for post data to return ? (await agent.PostData() ?) It might be that you are getting exceptions on your client side which get swallowed because of missing await.
> 
> There is nothing special about the postdata method, it just makes a normal http post.

Yes I am waiting for the post data return. This is how I call the method:
`const result = await this.agent.PostData(values, new Date());`

**Comment by kaischwetz** [comment]
> @kaischwetz
> 
> Can you please register your agent for diagnostics
> 
> https://opensource.mindsphere.io/docs/mindconnect-nodejs/cli/agent-diagnostic.html
> 
> (or using the application AgentDiagnostic on your launchpad), run the agent and see if there are any problems.
> 
> are you waiting for post data to return ? (await agent.PostData() ?) It might be that you are getting exceptions on your client side which get swallowed because of missing await.
> 
> There is nothing special about the postdata method, it just makes a normal http post.

Hey @sn0wcat,
thank you for the quick reply, you were right with your assumption about the async call of the method.  
I had thought about the async call of PostData, but I forgot that the superior call can not be a setInterval() function that can't make asynchronous calls.
I changed that and now everything works fine, thank you for that right impulse to the problem.

Best regards

Kai
